name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: fabacab/jekyll-builder-for-github-pages-action@master
        with:
          pre_build_commands: |
            #echo "Packaged bundler version: $(bundle --version)"
            #echo "Updating bundler..."
            #gem install bundler
            echo "[DEBUG] gem install nokogiri -v '1.8.5'"
            gem install nokogiri -v '1.8.5'
            echo "[DEBUG] bundle update jekyll-target-blank"
            bundle update jekyll-target-blank
            echo "[DEBUG] bundle update github-pages"
            bundle update github-pages
            echo "[DEBUG] bundle update html-pipeline"
            bundle update html-pipeline
 
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}



# source https://jekyllrb.com/docs/continuous-integration/github-actions/
